### ISSUE TITLE
You need a toolbox.json   Here is one that will work for this

### ISSUE THREAD

**Issue by fennectech** [Grarak/NXCord#2]
Just put this alongside exefs.nsp and tools like kosmos toolbox and tesla will pick it up
```
{
    "name"  : "NXcord",
    "tid"   : "5600000000000000",
    "requires_reboot": false
}
```

**Comment by Grarak** [comment]
https://github.com/Grarak/NXCord/commit/4ab86e196a26a309afb11f20044f589e36acbea9
