### ISSUE TITLE
Failed to parse login response

### ISSUE THREAD

**Issue by NickMaga** [Grarak/NXCord#3]
With every account i try to log in i get always failed to parse login response.
I even tried the bot method but it crashes because it says that my account it's too big (even tho it's a fresh account)

**Comment by Grarak** [comment]
What Atmosphere version are you using?

**Comment by KamiEpix** [comment]
I have the same issue im running the latest as of 4/9/2020

**Comment by Grarak** [comment]
> I have the same issue im running the latest as of 4/9/2020


> What Atmosphere version are you using?

**Comment by DerpySlurrpe** [comment]
> > I have the same issue im running the latest as of 4/9/2020
> 
> > What Atmosphere version are you using?

Im Guessing He Using 10.4

**Comment by Grarak** [comment]
I released a new version, to deal with crashes. I doubt it will fix the login problem though. Please use a bot if you can't get passed login.
