### ISSUE TITLE
Failed to parse login

### ISSUE THREAD

**Issue by DerpySlurrpe** [Grarak/NXCord#4]
Yo I cant login and im using atmosphere 10.5 And Firmware 9.20 tried login in but nothing working know whats up?

Could it be it not working because it not work with this Atmosphere ver or firmware or some of the files in homebrew maybe?

**Comment by DerpySlurrpe** [comment]
i also downgraded to atmoshere 10.3 to see if something would happen still dosent work

**Comment by Grarak** [comment]
Duplicate https://github.com/Grarak/NXCord/issues/3
